import type { Topic } from "../types";

export const HISTORY_TOPICS: Topic[] = [
  {
    id: "hist-khanate",
    subjectId: "history-kz",
    title: "Казахское ханство",
    grades: [7, 8, 9],
    summary: "Образование ханства, ключевые правители и свод законов «Жеті жарғы».",
    skills: ["Образование ханства", "Ханы и реформы", "Общественный строй"],
    theory: [
      "Казахское ханство было образовано в 1465 году султанами Кереем и Жанибеком, которые откочевали из ханства Абулхаира в Жетысу. Эта дата считается началом казахской государственности.",
      "При хане Касыме в начале XVI века ханство достигло наибольшего могущества: численность населения выросла до миллиона человек, а границы значительно расширились. Свод норм того времени известен как «Қасым ханның қасқа жолы».",
      "Хан Тауке в конце XVII века провёл правовую реформу и утвердил свод законов «Жеті жарғы» — семь установлений, регулировавших земельные, семейные и уголовные отношения.",
      "Казахский народ исторически делился на три жуза — Старший, Средний и Младший. Каждый жуз объединял группы родов и племён с общей территорией кочевания.",
    ],
    materials: [
      {
        title: "Лента времени Казахского ханства",
        kind: "theory",
        minutes: 8,
        summary: "Ключевые даты от 1465 года до присоединения к Российской империи.",
      },
      {
        title: "Ханы и их реформы",
        kind: "checklist",
        minutes: 6,
        summary: "Касым, Хакназар, Есим, Тауке — кто за что отвечает в билетах ЕНТ.",
      },
    ],
    tasks: [
      {
        id: "hist-khanate-1",
        topicId: "hist-khanate",
        type: "numeric",
        difficulty: 1,
        skill: "Образование ханства",
        prompt: "В каком году было образовано Казахское ханство? Укажите год цифрами.",
        answer: "1465",
        explanation:
          "Традиционной датой образования Казахского ханства считается 1465 год — откочёвка Керея и Жанибека в Жетысу.",
        minutes: 2,
      },
      {
        id: "hist-khanate-2",
        topicId: "hist-khanate",
        type: "single",
        difficulty: 1,
        skill: "Образование ханства",
        prompt: "Кто считается основателями Казахского ханства?",
        options: [
          "Абылай и Кенесары",
          "Керей и Жанибек",
          "Касым и Хакназар",
          "Тауке и Есим",
        ],
        answer: 1,
        explanation:
          "Основатели — султаны Керей и Жанибек. Абылай и Кенесары относятся к значительно более позднему периоду.",
        minutes: 2,
      },
      {
        id: "hist-khanate-3",
        topicId: "hist-khanate",
        type: "single",
        difficulty: 2,
        skill: "Ханы и реформы",
        prompt: "При каком хане Казахское ханство достигло наибольшего могущества в начале XVI века?",
        options: ["При хане Касыме", "При хане Тауке", "При хане Абылае", "При хане Есиме"],
        answer: 0,
        explanation:
          "При хане Касыме ханство усилилось, а его нормы вошли в историю как «Қасым ханның қасқа жолы».",
        minutes: 3,
      },
      {
        id: "hist-khanate-4",
        topicId: "hist-khanate",
        type: "single",
        difficulty: 2,
        skill: "Ханы и реформы",
        prompt: "С именем какого хана связан свод законов «Жеті жарғы»?",
        options: ["Касыма", "Есима", "Тауке", "Абылая"],
        answer: 2,
        explanation:
          "«Жеті жарғы» — семь установлений, принятых при хане Тауке в конце XVII века.",
        minutes: 3,
      },
      {
        id: "hist-khanate-5",
        topicId: "hist-khanate",
        type: "text",
        difficulty: 3,
        skill: "Общественный строй",
        prompt: "Как называется историческое объединение казахских родов и племён — Старший, Средний и Младший?",
        answer: "жуз",
        accepted: ["жүз", "жузы", "жуздар"],
        explanation:
          "Это жуз. Казахский народ исторически делился на три жуза, каждый со своей территорией кочевания.",
        minutes: 4,
      },
    ],
  },
  {
    id: "hist-modern",
    subjectId: "history-kz",
    title: "Независимый Казахстан",
    grades: [9, 10, 11],
    summary: "Независимость, Конституция, символы государства и ключевые реформы.",
    skills: ["Независимость", "Конституция", "Символы государства", "Экономические реформы"],
    theory: [
      "16 декабря 1991 года был принят конституционный закон о государственной независимости Республики Казахстан. Этот день отмечается как День Независимости.",
      "Национальная валюта тенге была введена в обращение 15 ноября 1993 года. Это позволило стране проводить самостоятельную денежно-кредитную политику.",
      "Действующая Конституция Республики Казахстан была принята на республиканском референдуме 30 августа 1995 года. Этот день отмечается как День Конституции.",
      "В 1997 году столица была перенесена из Алматы в Акмолу, которая позднее получила название Астана. Государственные символы страны — Флаг, Герб и Гимн.",
    ],
    materials: [
      {
        title: "Даты новейшей истории Казахстана",
        kind: "theory",
        minutes: 7,
        summary: "1991, 1993, 1995, 1997 — что произошло в каждый из этих годов.",
      },
      {
        title: "Государственные символы",
        kind: "checklist",
        minutes: 5,
        summary: "Флаг, Герб и Гимн: значение элементов и авторы символов.",
      },
    ],
    tasks: [
      {
        id: "hist-modern-1",
        topicId: "hist-modern",
        type: "numeric",
        difficulty: 1,
        skill: "Независимость",
        prompt: "В каком году Казахстан провозгласил государственную независимость? Укажите год цифрами.",
        answer: "1991",
        explanation:
          "Конституционный закон о государственной независимости был принят 16 декабря 1991 года.",
        minutes: 2,
      },
      {
        id: "hist-modern-2",
        topicId: "hist-modern",
        type: "numeric",
        difficulty: 1,
        skill: "Экономические реформы",
        prompt: "В каком году в Казахстане была введена национальная валюта тенге?",
        answer: "1993",
        explanation: "Тенге введён в обращение 15 ноября 1993 года.",
        minutes: 2,
      },
      {
        id: "hist-modern-3",
        topicId: "hist-modern",
        type: "numeric",
        difficulty: 2,
        skill: "Конституция",
        prompt: "В каком году была принята действующая Конституция Республики Казахстан?",
        answer: "1995",
        explanation:
          "Конституция принята на республиканском референдуме 30 августа 1995 года.",
        minutes: 3,
      },
      {
        id: "hist-modern-4",
        topicId: "hist-modern",
        type: "single",
        difficulty: 2,
        skill: "Символы государства",
        prompt: "Что относится к государственным символам Республики Казахстан?",
        options: [
          "Флаг, Герб и Гимн",
          "Флаг, Герб и печать",
          "Гимн, Герб и штандарт",
          "Флаг, Гимн и валюта",
        ],
        answer: 0,
        explanation:
          "Государственными символами являются Флаг, Герб и Гимн Республики Казахстан.",
        minutes: 3,
      },
      {
        id: "hist-modern-5",
        topicId: "hist-modern",
        type: "numeric",
        difficulty: 3,
        skill: "Независимость",
        prompt: "В каком году столица Казахстана была официально перенесена из Алматы в Акмолу?",
        answer: "1997",
        explanation:
          "Перенос столицы состоялся в 1997 году, а в 1998 году город получил название Астана.",
        minutes: 4,
      },
    ],
  },
];

const READING_PASSAGE =
  "Almaty is the largest city in Kazakhstan. Although Astana became the capital in 1997, Almaty remains the country's main business and cultural centre. Every year thousands of students move there to study at its universities.";

export const ENGLISH_TOPICS: Topic[] = [
  {
    id: "eng-tenses",
    subjectId: "english",
    title: "Времена английского глагола",
    grades: [7, 8, 9, 10, 11],
    summary: "Present Simple, Past Simple, Present Perfect и будущее время.",
    skills: ["Present Simple", "Past Simple", "Present Perfect", "Future forms"],
    theory: [
      "Present Simple описывает регулярные действия и факты. В третьем лице единственного числа к глаголу добавляется -s: he works, she goes. В отрицаниях и вопросах используется does, и тогда окончание -s исчезает.",
      "Past Simple описывает завершённое действие в прошлом. Правильные глаголы получают окончание -ed, неправильные меняют форму: write — wrote, go — went, take — took.",
      "Present Perfect (have/has + третья форма глагола) связывает прошлое с настоящим: результат важен сейчас. Маркеры: already, just, never, ever, yet.",
      "Для будущего используется will + инфинитив, конструкция be going to для планов и Future Perfect (will have + третья форма) для действия, завершённого к моменту в будущем.",
    ],
    materials: [
      {
        title: "Таблица трёх времён",
        kind: "theory",
        minutes: 6,
        summary: "Present Simple, Past Simple и Present Perfect в одной таблице с маркерами.",
      },
      {
        title: "Неправильные глаголы: топ-40",
        kind: "practice",
        minutes: 12,
        summary: "Самые частые неправильные глаголы, которые встречаются в тестах.",
      },
    ],
    tasks: [
      {
        id: "eng-tenses-1",
        topicId: "eng-tenses",
        type: "single",
        difficulty: 1,
        skill: "Present Simple",
        prompt: "Choose the correct form: She ___ to school every day.",
        options: ["go", "goes", "going", "gone"],
        answer: 1,
        explanation:
          "Present Simple, третье лицо единственного числа — к глаголу добавляется -s или -es: she goes.",
        minutes: 2,
      },
      {
        id: "eng-tenses-2",
        topicId: "eng-tenses",
        type: "single",
        difficulty: 1,
        skill: "Past Simple",
        prompt: "What is the Past Simple form of the verb «write»?",
        options: ["writed", "wrote", "written", "writing"],
        answer: 1,
        explanation:
          "Write — неправильный глагол: write — wrote — written. Форма written используется в Present Perfect и пассиве.",
        minutes: 2,
      },
      {
        id: "eng-tenses-3",
        topicId: "eng-tenses",
        type: "single",
        difficulty: 2,
        skill: "Present Perfect",
        prompt: "Choose the correct option: I ___ never ___ to London.",
        options: ["have / been", "has / be", "had / being", "am / been"],
        answer: 0,
        explanation:
          "Present Perfect строится как have/has + третья форма глагола. С местоимением I используется have, третья форма от be — been.",
        minutes: 3,
      },
      {
        id: "eng-tenses-4",
        topicId: "eng-tenses",
        type: "single",
        difficulty: 2,
        skill: "Present Simple",
        prompt: "Choose the grammatically correct sentence.",
        options: [
          "He don't like tea.",
          "He doesn't likes tea.",
          "He doesn't like tea.",
          "He not like tea.",
        ],
        answer: 2,
        explanation:
          "В третьем лице используется doesn't, а сам глагол остаётся без окончания -s: He doesn't like tea.",
        minutes: 3,
      },
      {
        id: "eng-tenses-5",
        topicId: "eng-tenses",
        type: "single",
        difficulty: 3,
        skill: "Future forms",
        prompt: "Choose the correct option: By 2030 Kazakhstan ___ a new technology hub.",
        options: ["will have built", "will building", "is build", "has build"],
        answer: 0,
        explanation:
          "Конструкция «by + время в будущем» требует Future Perfect: will have + третья форма глагола.",
        minutes: 4,
      },
    ],
  },
  {
    id: "eng-reading",
    subjectId: "english",
    title: "Чтение и понимание текста",
    grades: [8, 9, 10, 11],
    summary: "Главная мысль, детали и значение слов по контексту.",
    skills: ["Main idea", "Detail", "Vocabulary in context"],
    theory: [
      "Главная мысль текста обычно содержится в первом или последнем предложении абзаца. Ответ на вопрос про main idea всегда описывает текст целиком, а не одну деталь.",
      "Вопросы на детали проверяют конкретные факты: даты, числа, имена. Такие ответы нужно находить в тексте дословно, а не по памяти.",
      "Значение незнакомого слова определяется по контексту. Обратите внимание на соседние слова и на то, поддерживает предложение мысль или противопоставляет её.",
      "Слова although, however и but сигнализируют о противопоставлении. Они часто становятся ключом к правильному ответу в заданиях на понимание.",
    ],
    materials: [
      {
        title: "Стратегия чтения за 4 шага",
        kind: "checklist",
        minutes: 5,
        summary: "Сначала вопросы, потом текст: как экономить время на тесте.",
      },
      {
        title: "Слова-маркеры противопоставления",
        kind: "theory",
        minutes: 4,
        summary: "Although, however, despite — как они меняют смысл предложения.",
      },
    ],
    tasks: [
      {
        id: "eng-reading-1",
        topicId: "eng-reading",
        type: "single",
        difficulty: 1,
        skill: "Main idea",
        passage: READING_PASSAGE,
        prompt: "What is the main idea of the text?",
        options: [
          "Astana is the capital of Kazakhstan.",
          "Almaty is still the main business and cultural centre of the country.",
          "Students do not like living in Almaty.",
          "Kazakhstan has many large cities.",
        ],
        answer: 1,
        explanation:
          "Текст целиком посвящён роли Алматы. Упоминание Астаны — лишь деталь, вводимая словом although.",
        minutes: 3,
      },
      {
        id: "eng-reading-2",
        topicId: "eng-reading",
        type: "numeric",
        difficulty: 1,
        skill: "Detail",
        passage: READING_PASSAGE,
        prompt: "According to the text, in which year did Astana become the capital?",
        answer: "1997",
        explanation: "В тексте прямо сказано: «Astana became the capital in 1997».",
        minutes: 2,
      },
      {
        id: "eng-reading-3",
        topicId: "eng-reading",
        type: "single",
        difficulty: 2,
        skill: "Vocabulary in context",
        passage: READING_PASSAGE,
        prompt: "The word «remains» in the text is closest in meaning to…",
        options: ["leaves", "continues to be", "becomes", "stops"],
        answer: 1,
        explanation:
          "Remains здесь означает «продолжает оставаться». Слово leaves имеет противоположный смысл.",
        minutes: 3,
      },
      {
        id: "eng-reading-4",
        topicId: "eng-reading",
        type: "single",
        difficulty: 2,
        skill: "Detail",
        passage: READING_PASSAGE,
        prompt: "According to the text, why do thousands of students move to Almaty every year?",
        options: [
          "To find a job",
          "To study at its universities",
          "To visit relatives",
          "To watch sport competitions",
        ],
        answer: 1,
        explanation:
          "В последнем предложении сказано: «students move there to study at its universities».",
        minutes: 3,
      },
      {
        id: "eng-reading-5",
        topicId: "eng-reading",
        type: "single",
        difficulty: 3,
        skill: "Detail",
        passage: READING_PASSAGE,
        prompt: "Which statement is TRUE according to the text?",
        options: [
          "Almaty is the capital of Kazakhstan.",
          "Almaty is smaller than Astana.",
          "Almaty is the largest city in Kazakhstan.",
          "Almaty has no universities.",
        ],
        answer: 2,
        explanation:
          "Первое предложение текста прямо утверждает: «Almaty is the largest city in Kazakhstan». Столица с 1997 года — Астана.",
        minutes: 4,
      },
    ],
  },
];
